default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly
  # submodules: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      #  - id: end-of-file-fixer
      #  - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      #  - id: check-docstring-first
      #  - id: check-executables-have-shebangs
      #  - id: check-case-conflict
      #  - id: check-added-large-files
      - id: detect-private-key

  #- repo: https://github.com/astral-sh/ruff-pre-commit
  #  rev: "v0.1.9"
  #  hooks:
  #    - id: ruff
  #      name: Run Ruff (Flake8)
  #      args: ["--fix", "--preview"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: Run MyPy
        args: ["--show-error-codes"]

  #- repo: https://github.com/PyCQA/docformatter
  #  rev: v1.5.0
  #  hooks:
  #    - id: docformatter
  #      name: Format docstrings with Docformatter
  #      additional_dependencies: [tomli]
  #      args: ["--in-place"]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: Format code with Black

  #- repo: https://github.com/executablebooks/mdformat
  #  rev: 0.7.17
  #  hooks:
  #    - id: mdformat
  #      additional_dependencies:
  #        - mdformat-gfm
  #        - mdformat_frontmatter
